apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: jmeter
  name: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jmeter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: jmeter
    spec:
      imagePullSecrets:
      - name: dockersecret
      containers:
      - command:
        - cat
        image: muralivishnun/java:8-jdk
        imagePullPolicy: ""
        name: jmeter
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
