apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: telegraf
    spec:
      imagePullSecrets:
      - name: dockersecret
      containers:
      - image: muralivishnun/telegraf:latest
        imagePullPolicy: ""
        name: telegraf
        resources: {}
      hostname: telegraf-loadgenerator
      restartPolicy: Always
      serviceAccountName: ""
status: {}
