apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-setup
  name: grafana-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-setup
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: grafana-setup
    spec:
      containers:
      - env:
        - name: GF_PASSWORD
          value: admin
        - name: GF_USER
          value: admin
        image: sitespeedio/grafana-bootstrap:sitespeed.io-4.6
        imagePullPolicy: ""
        name: grafana-setup
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
