apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
  - name: "8857"
    port: 8857
    targetPort: 3000
  selector:
    io.kompose.service: grafana
status:
  loadBalancer: {}
