apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: graphite
  name: graphite
spec:
  ports:
  - name: "2003"
    port: 2003
    targetPort: 2003
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: graphite
status:
  loadBalancer: {}
