apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  ports:
  - name: "8653"
    port: 8653
    targetPort: 8086
  - name: 8653-tcp
    port: 8653
    targetPort: 8653
  selector:
    io.kompose.service: influxdb
status:
  loadBalancer: {}
