apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
      - image: influxdb
        imagePullPolicy: ""
        name: influxdb
        ports:
        - containerPort: 8086
        - containerPort: 8653
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: influxdb
        persistentVolumeClaim:
          claimName: influxdb
status: {}
