apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sitespeed-io
  name: sitespeed-io
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sitespeed-io
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: sitespeed-io
    spec:
      containers:
      - args:
        - -V
        image: sitespeedio/sitespeed.io
        imagePullPolicy: ""
        name: sitespeed.io
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sitespeed.io/
          name: sitespeed
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: sitespeed
        persistentVolumeClaim:
          claimName: sitespeed
status: {}
