apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: telegraf
    spec:
      containers:
      - image: telegraf
        imagePullPolicy: ""
        name: telegraf
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: telegraf-claim0
      hostname: telegraf-loadgenerator
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: telegraf-claim0
        persistentVolumeClaim:
          claimName: telegraf-claim0
status: {}
