apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: webpagetestagent
  name: webpagetestagent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webpagetestagent
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: webpagetestagent
    spec:
      containers:
      - env:
        - name: EXTRA_ARGS
          value: -vvvvv --shaper none
        - name: LOCATION
          value: Test
        - name: SERVER_URL
          value: http://wptserver:80/work/
        image: webpagetest/agent
        imagePullPolicy: ""
        name: wptagent
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
