apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose --file docker-compose-with-frontend.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: webpagetestagent
  name: webpagetestagent
spec:
  ports:
  - name: "4001"
    port: 4001
    targetPort: 80
  selector:
    io.kompose.service: webpagetestagent
status:
  loadBalancer: {}
