apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    run: jmeter-master
    jmeter_mode: master
  name: jmeter-master
spec:
  replicas: 1
  selector:
    run: jmeter-master
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: jmeter-master
    spec:
      containers:
      - image: cloudssky/jmeter-master
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: Always
        name: jmeter-master
        ports:
        - containerPort: 60000
          protocol: TCP
        volumeMounts:
          - name: loadtest
            mountPath: /jmeter/load_test
            subPath: "load_test"
      volumes:
      - name: loadtest
        configMap:
         name: jmeter-load-test
        resources: {}



